[package]
name = "git-svn-rs-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
svn-libsvn = []

[dependencies]
clap.workspace = true
fancy-regex.workspace = true
flate2.workspace = true
hex.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
vcpkg.workspace = true
